
####### acesso interno
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.Ambiente.ServerNameInteno10}}
spec:
  clusterIP: None
  selector:
   name: {{ .Values.Ambiente.Name10 }} ######## conecta ao deployment
  ports:
    - name: http-{{ .Values.Ambiente.PortContainer10 }}
      port:  {{ .Values.Ambiente.PortContainer10 }}
      targetPort:  {{ .Values.Ambiente.PortContainer10 }}
---
###### acesso via ip
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Ambiente.ServerNameInteno10}}-ip
spec:
  selector:
     name: {{ .Values.Ambiente.Name10 }}
  ports:
     - name: http
       protocol: TCP
       port:   {{ .Values.Ambiente.PortContainer10 }}
       nodePort: {{ .Values.Ambiente.PortServerLocal10}}
  type: NodePort
status:
